# Generated by Django 5.2.5 on 2026-02-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.TextField()),
                ('email', models.TextField()),
                ('phone', models.DecimalField(decimal_places=2, max_digits=10)),
                ('matric_number', models.CharField()),
            ],
        ),
    ]
