# Generated by Django 5.2.5 on 2026-02-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='email',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='fullname',
            field=models.CharField(),
        ),
    ]
