# Generated by Django 5.2.5 on 2026-02-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0002_alter_accounts_email_alter_accounts_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='matric_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
