# Generated by Django 5.2.5 on 2026-02-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0003_alter_accounts_matric_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
