# Generated by Django 5.2.5 on 2026-02-03 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0004_alter_accounts_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('cgpa', models.FloatField()),
                ('failed_courses', models.IntegerField(default=0)),
                ('registered_courses', models.IntegerField()),
                ('current_credit_load', models.IntegerField()),
                ('department', models.CharField(max_length=100)),
                ('past_courses', models.JSONField(default=list)),
                ('current_courses', models.JSONField(default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
