# Generated by Django 5.2.5 on 2026-02-04 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0005_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('cgpa', models.FloatField()),
                ('department', models.CharField(max_length=100)),
                ('registered_courses', models.IntegerField(default=0)),
                ('credit_load', models.IntegerField(default=0)),
                ('courses_failed', models.IntegerField(default=0)),
                ('cgpa_trend', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
