# Generated by Django 5.2.5 on 2026-02-04 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0006_studentprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
